/* Barry Sanders Collectors Hub service worker — V192 (auto-generated by build; do not hand-edit) */
const CACHE = 'bshub-V192';
/* A new SW installs and waits; the app shows an "Update available" prompt and
   posts 'skipWaiting' when the user accepts. */
self.addEventListener('install', e => {/* wait for user */});
self.addEventListener('message', e => { if (e.data === 'skipWaiting') self.skipWaiting(); });
/* On activate, delete every older cache so a stale shell can never linger. */
self.addEventListener('activate', e => e.waitUntil(
  caches.keys()
    .then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim())
));
/* Network-FIRST, bypassing the HTTP cache ({cache:'no-cache'} forces revalidation)
   so a freshly deployed version is always served when online; the cached copy is
   used only as an offline fallback. */
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  e.respondWith(
    fetch(req, { cache: 'no-cache' })
      .then(res => { const copy = res.clone(); caches.open(CACHE).then(c => { try { c.put(req, copy); } catch (x) {} }); return res; })
      .catch(() => caches.match(req).then(m => m || caches.match('./index.html') || caches.match('./')))
  );
});
